services:
  - type: web
    name: rupiksha-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5001
      - key: DB_HOST
        value: rupiksha-dubeyom1406-6e39.i.aivencloud.com
      - key: DB_PORT
        value: "27817"
      - key: DB_USER
        value: avnadmin
      - key: DB_PASS
        value: "[REDACTED_SECURE_PASSWORD]"
      - key: DB_NAME
        value: defaultdb
      - key: DB_SSL
        value: "true"
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_USER
        value: dubeyom1406@gmail.com
      - key: EMAIL_PASS
        value: "[REDACTED_APP_PASSWORD]"
      - key: FRONTEND_URL
        value: https://rupiksha.onrender.com
      - key: FAST2SMS_KEY
        value: "[REDACTED_API_KEY]"

  - type: static
    name: rupiksha
    env: static
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://rupiksha-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
